// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_OP_Web;

namespace Test_OP_Web.Migrations
{
    [DbContext(typeof(OptionContext))]
    [Migration("20220610083242_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TEST_OP.Anwser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Right")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anwser");
                });

            modelBuilder.Entity("TEST_OP.Option", b =>
                {
                    b.Property<int>("NumVar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("NumVar");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("TEST_OP.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FourId")
                        .HasColumnType("int");

                    b.Property<int?>("OneId")
                        .HasColumnType("int");

                    b.Property<int?>("OptionNumVar")
                        .HasColumnType("int");

                    b.Property<string>("QuestionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThreeId")
                        .HasColumnType("int");

                    b.Property<int?>("TwoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FourId");

                    b.HasIndex("OneId");

                    b.HasIndex("OptionNumVar");

                    b.HasIndex("ThreeId");

                    b.HasIndex("TwoId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("TEST_OP.Question", b =>
                {
                    b.HasOne("TEST_OP.Anwser", "Four")
                        .WithMany()
                        .HasForeignKey("FourId");

                    b.HasOne("TEST_OP.Anwser", "One")
                        .WithMany()
                        .HasForeignKey("OneId");

                    b.HasOne("TEST_OP.Option", null)
                        .WithMany("Questions")
                        .HasForeignKey("OptionNumVar");

                    b.HasOne("TEST_OP.Anwser", "Three")
                        .WithMany()
                        .HasForeignKey("ThreeId");

                    b.HasOne("TEST_OP.Anwser", "Two")
                        .WithMany()
                        .HasForeignKey("TwoId");

                    b.Navigation("Four");

                    b.Navigation("One");

                    b.Navigation("Three");

                    b.Navigation("Two");
                });

            modelBuilder.Entity("TEST_OP.Option", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
