version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  test_op_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_op
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2705
    ports:
      - "5432:5432"
    volumes:
      - ~/db_data:/var/lib/postgresql/data
